#-------------------------------
#   Shougo's plugins
#-------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'


[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# easy text object manipulating
[[plugins]]
repo = 'terryma/vim-expand-region'

# vim syntax for toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# vim help in Japanese 
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# swift
[[plugins]]
repo = 'apple/swift'

[[plugins]]
repo = 'keith/swift.vim'

[[plugins]]
repo = 'gfontenot/vim-xcode'

#[[plugins]]
#repo = 'landaire/deoplete-swift'

[[plugins]]
repo = 'mitsuse/autocomplete-swift'
depends = ['Shougo/deoplete.nvim']

# submode (used for changing window size etc.)
[[plugins]]
repo = 'kana/vim-submode'

# star search 
[[plugins]]
repo =  'nelstrom/vim-visual-star-search'

