[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'mitsuse/autocomplete-swift'
depends = ['Shougo/deoplete.nvim']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'apple/swift'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo =  'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
