#-------------------------------
#     dein_lazy.toml
#-------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_post_source = '''
	let g:deoplete#enable_camel_case = 0
	let g:deoplete#enable_ignore_case = 0
	let g:deoplete#enable_refresh_always = 0
	let g:deoplete#enable_smart_case = 1
	let g:deoplete#file#enable_buffer_path = 1
	let g:deoplete#max_list = 10000
	let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_post_source = '''
	nmap <C-k> <Plug>(neosnippet_jump)
	imap <C-k> <Plug>(neosnippet_jump_or_expand)
	smap <C-k> <Plug>(neosnippet_jump_or_expand)
	xmap <C-k> <Plug>(neosnippet_expand_target)
	let g:neosnippet#snippets_directory = expand('~/Dev/snippets/')
	autocmd BufRead,BufNewFile *.snip setlocal noexpandtab list
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'kannokanno/previm'
hook_post_source = '''
	let g:previm_open_cmd = 'open -a Firefox'
'''
on_ft = ['md','txt']



