#-------------------------------
#     dein_lazy.toml
#-------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_post_source = '''
	let g:deoplete#enable_camel_case = 0
	let g:deoplete#enable_ignore_case = 0
	let g:deoplete#enable_refresh_always = 0
	let g:deoplete#enable_smart_case = 1
	let g:deoplete#file#enable_buffer_path = 1
	let g:deoplete#max_list = 10000
	let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'kannokanno/previm'
hook_post_source = '''
	let g:previm_open_cmd = 'open -a Firefox'
'''
on_ft = ['md','txt']

[[plugins]]
repo = "let-def/vimbufsync"
on_ft = "coq"

#[[plugins]]
#repo = "the-lambda-church/coquille"
#on_ft = "coq"
#depends = ["vimbufsync"]

[[plugins]]
repo = "https://framagit.org/tyreunom/coquille"
on_ft = "coq"

