#-------------------------------
#   Shougo's plugins
#-------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_post_source = '''
	nmap <C-k> <Plug>(neosnippet_jump)
	imap <C-k> <Plug>(neosnippet_jump_or_expand)
	smap <C-k> <Plug>(neosnippet_jump_or_expand)
	xmap <C-k> <Plug>(neosnippet_expand_target)
	let g:neosnippet#snippets_directory = expand('~/Dev/snippets/')
	autocmd BufRead,BufNewFile *.snip setlocal noexpandtab list
'''
on_i  = 1

#------------------------------------
# Other useful plugins
#------------------------------------

# easy text object manipulating
[[plugins]]
repo = 'terryma/vim-expand-region'

# vim syntax for toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# vim help in Japanese 
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# git in vim
[[plugins]]
repo = 'tpope/vim-fugitive'


#-------------------
# swift
#-------------------
[[plugins]]
repo = 'apple/swift'
on_ft = ['swift']

#syntax
[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'gfontenot/vim-xcode'
on_ft = ['swift']

#syntax
#[[plugins]]
#repo = 'kballard/vim-swift'
#on_ft = ['swift']

[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = ['swift']

#[[plugins]]
#repo = 'mitsuse/autocomplete-swift'
#depends = ['Shougo/deoplete.nvim']

# submode (used for changing window size etc.)
[[plugins]]
repo = 'kana/vim-submode'

# star search 
[[plugins]]
repo =  'nelstrom/vim-visual-star-search'

# syntax check
[[plugins]]
repo = 'scrooloose/syntastic'

# deoplete clang
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c','cpp','m','mpp']

